# Generated by Django 2.1.3 on 2018-11-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_value', models.CharField(db_column='s_value', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(db_column='l_name', max_length=32, null=True)),
                ('f_name', models.CharField(db_column='f_name', max_length=32, null=True)),
                ('gender', models.CharField(db_column='gender', max_length=10, null=True)),
                ('m_name', models.CharField(db_column='m_name', max_length=32, null=True)),
                ('email', models.EmailField(db_column='email', max_length=254, null=True)),
                ('b_num', models.IntegerField(db_column='b_num', null=True)),
                ('ap', models.IntegerField(db_column='ap', null=True)),
                ('tel', models.CharField(db_column='tel', max_length=24, null=True)),
                ('job', models.CharField(db_column='job', max_length=32, null=True)),
                ('post', models.CharField(db_column='post', max_length=32, null=True)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='pb.city_table')),
            ],
        ),
        migrations.CreateModel(
            name='street_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_value', models.CharField(db_column='s_value', max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='phonebook',
            name='street',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='street', to='pb.street_table'),
        ),
    ]
